/*
* Generated file
*
* Generated from: yang module name: neutron-hostconfig-vpp-provider-impl yang module local name: neutron-hostconfig-vpp-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Jan 20 18:12:15 CET 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.neutron_hostconfig_vpp_provider.impl;
public class NeutronHostconfigVppProviderModuleFactory extends org.opendaylight.controller.config.yang.config.neutron_hostconfig_vpp_provider.impl.AbstractNeutronHostconfigVppProviderModuleFactory {

}
